<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php /** @var $block \Kozeta\Currency\Block\Image */ ?>

<img class="photo image"
        <?= /* @noEscape */ $block->getCustomAttributes(); ?>
     src="<?= /* @noEscape */ $block->getImageUrl(); ?>"
     width="<?= /* @noEscape */ $block->getWidth(); ?>"
     height="<?= /* @noEscape */ $block->getHeight(); ?>"
     alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true); ?>" />
