<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php /** @var $block \Kozeta\Currency\Block\Image */ $k=0; ?>

<span class="image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth()?>px;">
    <span class="image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100 * $k); ?>%;">
        <img class="image-photo"
                <?= /* @escapeNotVerified */ $block->getCustomAttributes(); ?>
             src="<?= /* @escapeNotVerified */ $block->getImageUrl(); ?>"
             width="<?= /* @escapeNotVerified */ $block->getResizedImageWidth(); ?>"
             height="<?= /* @escapeNotVerified */ $block->getResizedImageHeight(); ?>"
             alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true); ?>"/></span>
</span>
