<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php
/**
 * @var $block \Kozeta\Currency\Block\Adminhtml\System\Currency\Rate\Matrix
 */
?>

<?php
    $_rates = $block->_getDisplayRates();
    $_newRates = $this->getNewRates();
?>

<?php if (empty($_rates)) : ?>
    <div class="message message-warning warning"><p><?= /* @escapeNotVerified */ __('You must first configure currency options before being able to see currency rates.') ?></p></div>
<?php else : ?>
    <form name="rateForm" id="rate-form" method="post" action="<?= /* @escapeNotVerified */ $block->getRatesFormAction() ?>">
        <?= $block->getBlockHtml('formkey') ?>
        
<?php
    $ac = $block->getAllowedCurrencies();
    $dc = $block->getDefaultCurrencies();
    $coins = $block->getCoinsInRow();
    $rows = $block->getRows();
?>  
<?php $j = 1; for ($i = 1; $i <= $rows; $i++) : ?>
        <div class="admin__control-table-wrapper"><br />
            <table class="admin__control-table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <?php $_i = 0; foreach ($ac as $k => $_currencyCode) : ?>
                            <th><span><?= /* @escapeNotVerified */ $_currencyCode ?></span></th>
                            <?php
                                $_i++;
                                unset($ac[$k]);
                            if ($_i == $coins) {
                                $_i = 0;
                                break;
                            }?>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <?php $_j = 0; foreach ($dc as $_currencyCode) : ?>
                <tr>
                    <?php if (isset($_rates[$_currencyCode]) && is_array($_rates[$_currencyCode])) : ?>
                        <?php foreach ($_rates[$_currencyCode] as $_code => $_value) : ?>
                            <?php if (++$_j == 1) : ?>
                                <td><span class="admin__control-support-text"><?= /* @escapeNotVerified */ $_currencyCode ?></span></td>
                            <?php endif; //print_r($_value)?>
                                <td>
                                    <input type="text"
                                           name="rate[<?= /* @escapeNotVerified */ $_currencyCode ?>][<?= /* @escapeNotVerified */ $_code ?>]"
                                           value="<?= ($_currencyCode == $_code) ? '1.0000' : (isset($_newRates[$_currencyCode][$_code]) ? (float) $_newRates[$_currencyCode][$_code] : (float) $_value['rate'] ?: '') ?>"
                                           class="admin__control-text"
                                            <?= ($_currencyCode == $_code) ? ' disabled' : '' ?> />
                                    <?php if (!empty($_newRates) && $_currencyCode != $_code && isset($_value['rate'])) : ?>
                                    <div class="admin__field-note"><?= /* @escapeNotVerified */ __('Old rate:') ?> <b><?= /* @escapeNotVerified */ (float) $_value['rate'] ?></b></div>
                                    <?php endif; ?>
                                    <?php if ($_code != $_currencyCode):?>
                                    <div class="admin__field-note"><?= /* @escapeNotVerified */ __('Updated at:') ?> <b><?= /* @escapeNotVerified */ $_value['updated_at'] ?></b></div>
                                    <?php endif; ?>
                                </td>
<?php
unset($_rates[$_currencyCode][$_code]);
if ($_j == $coins) {
    $_j = 0;
    break;
} ?>
                        <?php endforeach;
$_j = 0; ?>                        
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
<?php endfor; ?>
    </form>
<?php endif; ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#rate-form').mage('form').mage('validation');

});
</script>
