<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php
/**
 * @var $block \Kozeta\Currency\Block\Adminhtml\System\Currency\Rate\Matrix
 */
?>

<?php
    $_rates = $block->getDisplayRates();
    $_newRates = $block->getNewRates();
?>

<?php if (empty($_rates)) : ?>
    <div class="message message-warning warning"><p><?= /* @noEscape */ __('You must first configure currency options before being able to see currency rates.') ?></p></div>
<?php else : ?>
    <form name="rateForm" id="rate-form" method="post" action="<?= /* @noEscape */ $block->getRatesFormAction() ?>">
        <?= $block->getBlockHtml('formkey') ?>
        
    <?php
        $dc = $block->getBaseCurrencies();
        $coins = $block->getCoinsInRow();
    ?>
    <?php $_j = 0; foreach ($dc as $_baseCode => $ac) : ?>
        <?php
        $ac = $block->getCurrencies($_baseCode);
        $_ac = $ac;
        $rows = $block->getRows($_baseCode);
        ?>
        <?php if ($ac) : ?>
        <div><br /><h3><?= /* @noEscape */ __('Base currency') . ': ' . $_baseCode ?></h3></div>
    <?php endif; ?>
        <?php $j = 1; for ($i = 1; $i <= $rows; $i++) : ?>
        <div class="admin__control-table-wrapper"><br />
            <table class="admin__control-table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <?php $_i = 0; foreach ($ac as $k => $_code) : ?>
                            <th><span><?= /* @noEscape */ $_code ?></span></th>
                            <?php
                                $_i++;
                                unset($ac[$k]);
                            if ($_i == $coins) {
                                $_i = 0;
                                break;
                            }?>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <?php //$_j = 0; foreach ($dc as $_baseCode) : ?>
                <tr>
                    <?php if (isset($_rates[$_baseCode]) && is_array($_rates[$_baseCode])) : ?>
                        <?php foreach ($_ac as $k => $_code) : ?>
                            <?php if (++$_j == 1) : ?>
                                <td><span class="admin__control-support-text"><?= /* @noEscape */ $_baseCode ?></span></td>
                            <?php endif; ?>
                                <td>
                                    <input type="text"
                                           name="rate[<?= /* @noEscape */ $_baseCode ?>][<?= /* @noEscape */ $_code ?>]"
                                           value="<?php
                                            if (isset($_newRates[$_baseCode][$_code])) {
                                                /* @noEscape */ echo $block->formatDecimal($_newRates[$_baseCode][$_code]);
                                            } elseif (isset($_rates[$_baseCode][$_code]['rate'])) {
                                                /* @noEscape */ echo $block->formatDecimal($_rates[$_baseCode][$_code]['rate']);
                                            }
                                            ?>"
                                           class="admin__control-text"
                                            <?= ($_baseCode == $_code) ? ' disabled' : '' ?> />
                            <?php if (!empty($_newRates) && $_baseCode != $_code && isset($_rates[$_baseCode][$_code]['rate'])) : ?>
                                <div class="admin__field-note"><?= /* @noEscape */ __('Old rate:') ?> <b><?= /* @noEscape */ $block->formatDecimal($_rates[$_baseCode][$_code]['rate']) ?></b></div>
                            <?php endif; ?>
                            <?php if ($_code != $_baseCode && isset($_rates[$_baseCode][$_code]['updated_at'])) :?>
                                <div class="admin__field-note"><?= /* @noEscape */ __('Updated at:') ?> <b><?= /* @noEscape */ isset($_rates[$_baseCode][$_code]['updated_at']) ? $_rates[$_baseCode][$_code]['updated_at'] : '&nbsp;' ?></b></div>
                                <div class="admin__field-note"><?= /* @noEscape */ __('Service:') ?> <b>

                                <?php /* @escapeNotVerified */
                                $serviceName = $block->getServiceNames();
                                if (isset($serviceName[$_rates[$_baseCode][$_code]['currency_converter_id']])) {
                                    /* @noEscape */ echo $serviceName[$_rates[$_baseCode][$_code]['currency_converter_id']];
                                } else {
                                    echo '&nbsp;';
                                } ?></b></div>

                            <?php else : ?>
                                <div class="admin__field-note">&nbsp;</div>
                                <div class="admin__field-note">&nbsp;</div>
                            <?php endif; ?>
                            </td>
                            <?php
                            unset($_rates[$_baseCode][$_code]);
                            unset($_ac[$k]);
                            if ($_j == $coins) {
                                $_j = 0;
                                break;
                            } ?>
                        <?php endforeach; // Allowed currency ?>
                        <?php $_j = 0; ?>
                    <?php endif; ?>
                </tr>
                
            </table>
        </div>
        <?php endfor; ?>
    <?php endforeach; // Base currency ?>
    </form>
<?php endif; ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#rate-form').mage('form').mage('validation');

});
</script>
