<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php
/**
 * @var $block \Kozeta\Currency\Block\Adminhtml\System\Currency\Rate\Matrix
 */
?>

<?php
    $_rates = $block->_getDisplayRates();
    $_newRates = $this->getNewRates();
?>

<?php if (empty($_rates)) : ?>
    <div class="message message-warning warning"><p><?= /* @escapeNotVerified */ __('You must first configure currency options before being able to see currency rates.') ?></p></div>
<?php else : ?>
    <form name="rateForm" id="rate-form" method="post" action="<?= /* @escapeNotVerified */ $block->getRatesFormAction() ?>">
        <?= $block->getBlockHtml('formkey') ?>
        
<?php
    $ac = $block->getAllowedCurrencies();
    $_ac = $ac;
    $dc = $block->getDefaultCurrencies();
    $coins = $block->getCoinsInRow();
    $rows = $block->getRows();
?>
<?php $j = 1; for ($i = 1; $i <= $rows; $i++) : ?>
        <div class="admin__control-table-wrapper"><br />
            <table class="admin__control-table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <?php $_i = 0; foreach ($ac as $k => $_currencyCode) : ?>
                            <th><span><?= /* @escapeNotVerified */ $_currencyCode ?></span></th>
                            <?php
                                $_i++;
                                unset($ac[$k]);
                            if ($_i == $coins) {
                                $_i = 0;
                                break;
                            }?>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <?php $_j = 0; foreach ($dc as $_currencyCode) : ?>
                <tr>
                    <?php if (isset($_rates[$_currencyCode]) && is_array($_rates[$_currencyCode])) : ?>
                        <?php foreach ($_ac as $k => $_code) : ?>
                            <?php if (++$_j == 1) : ?>
                                <td><span class="admin__control-support-text"><?= /* @escapeNotVerified */ $_currencyCode ?></span></td>
                            <?php endif; ?>
                                <td>
                                    <input type="text"
                                           name="rate[<?= /* @escapeNotVerified */ $_currencyCode ?>][<?= /* @escapeNotVerified */ $_code ?>]"
                                           value="<?php if ($_currencyCode == $_code){
                                                            echo 1;
                                                        }
                                                        elseif (isset($_newRates[$_currencyCode][$_code])) {
                                                            echo $_newRates[$_currencyCode][$_code];
                                                        }
                                                        elseif (isset($_rates[$_currencyCode][$_code]['rate'])) {
                                                            echo (float) $_rates[$_currencyCode][$_code]['rate'];
                                                        } ?>"
                                           class="admin__control-text"
                                            <?= ($_currencyCode == $_code) ? ' disabled' : '' ?> />
                                    <?php if (!empty($_newRates) && $_currencyCode != $_code && isset($_rates[$_currencyCode][$_code]['rate'])) : ?>
                                    <div class="admin__field-note"><?= /* @escapeNotVerified */ __('Old rate:') ?> <b><?= /* @escapeNotVerified */ (float) $_rates[$_currencyCode][$_code]['rate'] ?></b></div>
                                    <?php endif; ?>
                                    <?php if ($_code != $_currencyCode && isset($_rates[$_currencyCode][$_code]['updated_at'])):?>
                                    <div class="admin__field-note"><?= /* @escapeNotVerified */ __('Updated at:') ?> <b><?= /* @escapeNotVerified */ isset($_rates[$_currencyCode][$_code]['updated_at']) ? $_rates[$_currencyCode][$_code]['updated_at'] : '&nbsp;' ?></b></div>
                                    <div class="admin__field-note"><?= /* @escapeNotVerified */ __('Service:') ?> <b><?= /* @escapeNotVerified */ isset($_rates[$_currencyCode][$_code]['currency_converter_id']) ? $_rates[$_currencyCode][$_code]['currency_converter_id'] : '&nbsp;' ?></b></div>
                                    <?php else: ?>
                                    <div class="admin__field-note">&nbsp;</div>
                                    <div class="admin__field-note">&nbsp;</div>
                                    <?php endif; ?>
                                </td>
<?php
unset($_rates[$_currencyCode][$_code]);
unset($_ac[$k]);
if ($_j == $coins) {
    $_j = 0;
    break;
} ?>
                        <?php endforeach; ?>
                        <?php $_j = 0; ?>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
<?php endfor; ?>
    </form>
<?php endif; ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#rate-form').mage('form').mage('validation');

});
</script>
