<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php /** @var \Kozeta\Currency\Block\Coin\ListCoin\Rss\Link $block */?>
<?php if ($block->isRssEnabled()) : ?>
    <a href="<?= /* @noEscape */ $block->getLink() ?>" class="coins action link rss">
        <span><?= /* @noEscape */ __('Subscribe to RSS Feed') ?></span>
    </a>
<?php endif; ?>
