<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */

// @codingStandardsIgnoreFile

//** @var Kozeta\Currency\Block\Coin\ListCoin $block */ 
?>


<?php 
    $_coins = $block->getCoins();
    $_rates = $block->_getRates();
?>

<div class="coins">
    <div class="list-base-currency"><strong><?= __('Base currency') ?>:</strong>&nbsp;<span><?= $block->getBaseCurrencyCode(); ?></span></div>
    <div class="list-default-currency"><span>&nbsp;</span></div>
    <?php if ($_coins->getSize() > 0) :?>
        <?php if ($_coins->getSize() > 10) :?>
        <div class="kozeta-currency-coins-toolbar toolbar top"><?= /* @escapeNotVerified */ $block->getPagerHtml(); ?></div>
        <?php endif; ?>
        <div class="kozeta-currency-coins-list-container">
            <table class="currency-coins-list-table">
            <tr>
                <th>&nbsp;</th>
                <th><?= /* @noEscape */ __('Name') ?> / <?= /* @noEscape */ __('Code') ?></th>
                
                <th><?= /* @escapeNotVerified */ __('Rate %1', $block->getBaseCurrencyCode()) ?></th> 
                <th><?= /* @escapeNotVerified */ __('Rate to %1', $block->getBaseCurrencyCode()) ?></th>
                <th><?= /* @noEscape */ __('Updated at') ?><br>(<a href="https://www.timeanddate.com/worldclock/timezone/utc" rel="nofollow" target="_blank">UTC</a>)</th> 
                </tr>
            <?php foreach ($_coins as $_coin) : 
                    $a_tag = '';
                    $_a_tag = '';
                    if ($block->getEnableCoinPages()) {
                        $a_tag = '<a href="' .  $_coin->getCoinUrl() . '">';
                        $_a_tag = '</a>';
                    }
            ?>

                <?php /** @var Kozeta\Currency\Model\Coin $_coin */ ?>
                <?php /* <div class="kozeta-currency-coin-list-item"> */ ?>
                <tr>
                    <td><?= /* @escapeNotVerified */ $a_tag . $block->getImage($_coin, 'coin_view', ['width' => 40, 'height' => 40, 'type' => 'avatar'])->toHtml() . $_a_tag ; ?></td>
                    <td><?= /* @escapeNotVerified */ $a_tag . __($_coin->getName()) . $_a_tag; ?>
                        <?php if($_coin->getSymbol()):?>
                            (<?= /* @escapeNotVerified */ $_coin->getSymbol(); ?>)
                        <?php endif; ?>
                        <br />
                        <?= /* @escapeNotVerified */ $_coin->getCode(); ?></td>
                    <td><?php echo !empty($_rates[$_coin->getCode()]['rate']) ? (float) $_rates[$_coin->getCode()]['rate'] : __('N/A'); ?></td>
                    <td><?php echo !empty($_rates[$_coin->getCode()]['rate']) ? (float) (1 / $_rates[$_coin->getCode()]['rate']) : __('N/A'); ?></td>
                    <td><?php if ($_coin->getCode() == $block->getBaseCurrencyCode()) { echo __('N/A');} elseif (!empty($_rates[$_coin->getCode()])) {if (!empty($_rates[$_coin->getCode()]['updated_at'])) echo $_rates[$_coin->getCode()]['updated_at'];} else {echo __('N/A');} ?></td>
                <?php /* </div> */ ?>
            <?php endforeach;?>
            </table>
        </div>
        <?php if ($_coins->getSize() > 10) :?>
        <div class="kozeta-currency-coins-toolbar toolbar bottom"><?= /* @escapeNotVerified */ $block->getPagerHtml(); ?></div>
        <?php endif; ?>
    <?php else : ?>
        <?= /* @escapeNotVerified */ __('There are no active currencies at this moment');?>
    <?php endif;?>
</div>
