<?php
/**
 * @author Kozeta Team
 * @copyright Copyright (c) 2019 Kozeta (https://www.kozeta.lt)
 * @package Kozeta_Curency
 */
?>
<?php /** @var \Kozeta\Currency\Block\Coin\ViewCoin $block */ ?>
<?php
    $_coin = $block->getCurrentCoin();
    $rate = $block->_getRate($_coin->getCode());
if (empty($rate)) {
    $rate = [
            'rate' => __('N/A'),
            '_rate' => __('N/A'),
            'updated_at' => __('N/A'),
        ];
} else {
    $rate = $rate[$_coin->getCode()];
    $rate['rate'] = (float)$rate['rate'];
    $rate['_rate'] = 1 / $rate['rate'];
    $rate['updated_at'] = $rate['updated_at'] . ' (<a href="https://www.timeanddate.com/worldclock/timezone/utc" rel="nofollow" target="_blank">UTC</a>)';
}
?>
<div class="coin-view">
    <div class="coin-avatar coin-details">
        <?= $block->getImage($_coin, 'coin_view', ['width' => 60, 'height' => 60, 'type' => 'avatar'])->toHtml(); ?>
    </div>

    <div class="coin-name coin-details">
        <strong><?= /* @noEscape */ __('Name') ?></strong>: <?= $block->escapeHtml($_coin->getName());?>
    </div>

    <div class="coin-code coin-details">
        <strong><?= /* @noEscape */ __('Code') ?></strong>: <?= $block->escapeHtml($_coin->getCode());?>
    </div>

    <div class="coin-symbol coin-details">
        <strong><?= /* @noEscape */ __('Symbol') ?></strong>: <?= $block->escapeHtml($_coin->getSymbol()) ?: $block->escapeHtml(__('N/A')) ;?>
    </div>

    <?php
        $isFiat = $_coin->getIsFiat();
        $iconNameFiat = $isFiat === true ? 'yes16x16.png' : 'no16x16.png';
        $iconPath = $block->getViewFileUrl('Kozeta_Currency::icons/'. $iconNameFiat);
        
    ?>
    <div class="coin-isFiat coin-details">
        <strong><?= /* @noEscape */ __('Is Fiat') ?></strong>: <img src="<?= /* @escapeNotVerified */ $iconPath; ?>" />
    </div>
    
    <?php if ($isFiat !== true) : ?>
    <div class="coin-type coin-details">
        <strong><?= /* @noEscape */ __('Type') ?></strong>: <?= /* @escapeNotVerified */ $_coin->getAttributeText('type');?>
    </div>
    <?php endif;?>
    
    <?php if ($_coin->getCode() != $block->_getBaseCurrencyCode()) : ?>
    <div class="coin-rate coin-details">
        <strong><?= /* @noEscape */ $block->escapeHtml(__('Current exchange rate to %1', $block->_getBaseCurrencyCode())) ?></strong>: <?= /* @escapeNotVerified */ $rate['_rate']; ?>
    </div>
    
    <div class="coin-rate coin-details">
        <strong><?= /* @noEscape */ __('Last updated') ?></strong>: <?= /* @noEscape */ $rate['updated_at']; ?>
    </div>
    <?php endif;?>

    <div class="coin-txfee coin-details">
        <strong><?= /* @noEscape */ __('Precision') ?></strong>: <?= /* @escapeNotVerified */ $_coin->getPrecision();?>
    </div>

    <div class="coin-isActive coin-details">
        <strong><?= /* @noEscape */ __('Status') ?></strong>: <?= /* @escapeNotVerified */ ($_coin->getIsActive())? __('Active'): __('Inactive');?>
    </div>
    
    <?php if ($isFiat !== true) : ?>
    <div class="coin-txfee coin-details">
        <strong><?= /* @noEscape */ __('Transactioin fee') ?></strong>: <?= /* @escapeNotVerified */ $_coin->getTxfee();?>
    </div>

    <div class="coin-rate coin-details">
        <strong><?= /* @noEscape */ __('Min. number of confirmations') ?></strong>: <?= /* @escapeNotVerified */ $_coin->getMinconf();?>
    </div>
    <?php endif;?>
    
    
    <?php
        $iconNameRss = $_coin->getInRss() ? 'yes16x16.png' : 'no16x16.png';
        $iconPath = $block->getViewFileUrl('Kozeta_Currency::icons/'. $iconNameRss);
    ?>
    <div class="coin-inRss coin-details">
        <strong><?= /* @noEscape */ __('Included into RSS feed') ?></strong>: <img src="<?= /* @escapeNotVerified */ $iconPath; ?>" />
    </div>
    <?php if ($_coin->getProcessedDescription()) : ?>
    <div class="coin-description coin-details">
        <strong><?= /* @noEscape */ __('Description') ?></strong>: 
        <div class="coin__description-content"><?= /* @escapeNotVerified */ $_coin->getProcessedDescription();?></div>
    </div>
    <?php endif; ?>

</div>
